version: "3.9"
services:
  db:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - backend

  go:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge